
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "stevelouie.com"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: /

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Steve Louie"
title: "Steve Louie"
description: "Steve Louie's personal site."
keywords: "steve, louie"
favicon: "/img/favicon.ico"

################
# Header layout #
################

#black-favicon: "/img/black-lab-glass.ico"

# background-img: ""

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: False
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 9
start-delay: 200
delete-delay: 8000
# lines: # You can add HTML Tags in the Text

# me-img: "/img/jetpacktocat.png"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

me-img: "https://github.com/stephenrlouie.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "https://github.com/stephenrlouie.png?size=36"
icon-48p: "https://github.com/stephenrlouie.png?size=48"
icon-72p: "https://github.com/stephenrlouie.png?size=72"
icon-96p: "https://github.com/stephenrlouie.png?size=96"
icon-144p: "https://github.com/stephenrlouie.png?size=144"
icon-192p: "https://github.com/stephenrlouie.png?size=192"

########
# Blog #
########

enable-gesture-navigation: False

# post-preview-words: 96

# paginate: 5

email-share: True
fb-share: False
twitter-share: True
linkedin-share: True
reddit-share: False
google-plus-share: False
tumblr-share: False
pinterest-share: False
pocket-share: True
vkontakte-share: False

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/bose.jpg"
    date: "Winter 2018 - Present"
    description: "Bose: Cloud Engineer"
  - image: "/img/timeline/kubeconEU2018.jpg"
    date: "Spring 2018"
    description: "Kubecon Presentation: Bringing Cloud-Native Applications to the Edge of the Network"
  - image: "/img/timeline/csco.jpg"
    date: "2015 - 2018"
    description: "Cisco: Software Engineer"
  - image: "/img/timeline/lehigh.png"
    date: "2015"
    description: "Lehigh University: Masters of Engineering: Computer Science"
  - image: "/img/timeline/msft.png"
    date: "May 2014"
    description: "Microsoft: SDET Intern"
  - image: "/img/timeline/lehigh.png"
    date: "May 2014"
    description: "Lehigh University: Bachelor of Science: Integrated Business and Engineering"
  - image: "/img/timeline/bd.jpg"
    date: "Summer 2013"
    description: "Becton Dickinson: Technical Development Intern"
  - image: "/img/timeline/ng.jpg"
    date: "Summer 2012"
    description: "Northrop Grumman: Software Engineer Intern"

# First image of the Timeline

timeline-img: "/img/timeline/lehigh.png"
timeline-date: 2010
timeline-description: "Start at Lehigh University"

###########
# Contact #
###########

email: "steve@stevelouie.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Steve Louie: Husband, Cloud Engineer, Gopher, Corgi Owner, Gamer, Lindy Hopper"
author_blurb_image: "https://github.com/stephenrlouie.png?size=500"

##################
# Social Buttons #
##################

social:
  - title: "twitter"
    url: https://twitter.com/Stephen_Louie
  - title: "github"
    url: https://github.com/stephenrlouie
  - title: "linkedin"
    url: https://www.linkedin.com/in/stephenrlouie

############
# 404 page #
############

err-404-img: "../img/404.jpg"

##################
# GPG on Keybase #
##################

# keybase-username: johnsmith
# keybase-in-social: True
# keybase-in-footer: True

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

# paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
